DebugMode: false
Hunter:
  Prefix: '&C'
  DisplayName: 'Hunter'
Runner:
  Prefix: '&A'
  DisplayName: 'Runner'
RunnerPrisoner:
  Prefix: '&A'
  DisplayName: 'RunnerPrisoner'
OtherPlayer:
  Prefix: '&F'
  DisplayName: 'OtherPlayer'  